language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

matrix:
  allow_failures:
    - php: 7

services:
  - mysql

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - composer install
  - mysql -e 'create database fuelphp_orm_tests;'

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7" ]; then vendor/bin/codecept run unit --coverage-xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "7" ]; then vendor/bin/codecept run unit; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7" ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_log/coverage.xml; fi;'

notifications:
  irc: "irc.freenode.org#fuelphp-status"
